### ISSUE TITLE
Disabling DeadCodeSniff

### ISSUE THREAD

**Issue by tomasnorre** [martin-helmich/typo3-typoscript-lint#1] opened 2015-10-27 18:00 UTC
Hi,

First I really like you work here, and I'm about to implement it as part of my Automated QA, Thanks. :+1: 

This is more a question that an issue, hope it's ok to address it here.

I want to allow comments in my TypoScript files, and therefor my tslint.yml looks like following: 

```
sniffs:
  - class: Indentation
    parameters:
      useSpaces: true
      indentPerLevel: 4
  - class: OperatorWhitespace
  - class: RepeatingRValue
  - class: DuplicateAssignment
  - class: NestingConsistency
``` 

So right now it's basically just a copy of you tslint.dist.yml which the - class: DeadCode removed.

But when running the linter, with this tslint.yml as -c (config file) input, it still complain about the DeadCode/Comments.. 

If I changes useSpaces or indentPerLevel it instantly changes the responses I get from linting.

Is there something logically i'm completely missing in this tool?

**Comment by martin-helmich** [comment] 2015-10-28 07:58
Thanks for the feedback! It's been a while since I've been working on
this, but I'll try to have a look as soon as I get the chance.

Am 27.10.2015 um 19:00 schrieb Tomas Norre Mikkelsen:

**Comment by tomasnorre** [comment] 2015-10-28 12:05
Thanks, Let me know if i can help in any way.. I will dig into it my self, i'll let you know if i find the problem :) It could be just me.

**Comment by martin-helmich** [comment] 2015-10-30 20:03
I've been able to pinpoint the issue; the problem is that a local configuration file -- if existent -- will still be merged with the distributed configuration file that is shipped with this package (and which still contains all possible sniffs).

I've introduced an additional configuration option in #2. Please have a look if this fixes your problem. :)

**Comment by tomasnorre** [comment] 2015-10-31 11:04
Thanks, I'll check

**Closed** 2015-11-04 19:29 UTC

**Comment by martin-helmich** [comment] 2015-11-04 19:30
I'm assuming this issue to be resolved with #2. Feel free to reopen this issue if that should not be the case.

**Comment by tomasnorre** [comment] 2015-11-05 13:55
Sorry forgot to follow up on that..
